//! Ingestion endpoints
//!
//! Handle document ingestion from files, text, and URLs.

use axum::{
    extract::{Multipart, Path, State},
    Json,
};
use reasondb_core::llm::ReasoningEngine;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tracing::info;
use utoipa::ToSchema;

use crate::{
    error::{ApiError, ApiResult, ErrorResponse},
    jobs::{IngestFileRequest, JobRequest, JobStatusResponse},
    state::AppState,
};

/// Response for ingestion operations
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct IngestResponse {
    /// Unique document ID
    #[schema(example = "doc_abc123")]
    pub document_id: String,
    /// Document title
    #[schema(example = "Machine Learning Fundamentals")]
    pub title: String,
    /// Total number of nodes in the tree
    #[schema(example = 42)]
    pub total_nodes: usize,
    /// Maximum depth of the tree
    #[schema(example = 4)]
    pub max_depth: usize,
    /// Ingestion statistics
    pub stats: IngestStats,
}

/// Statistics from ingestion
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct IngestStats {
    /// Characters extracted from source
    #[schema(example = 50000)]
    pub chars_extracted: usize,
    /// Text chunks created
    #[schema(example = 25)]
    pub chunks_created: usize,
    /// Tree nodes created
    #[schema(example = 42)]
    pub nodes_created: usize,
    /// Summaries generated by LLM
    #[schema(example = 42)]
    pub summaries_generated: usize,
    /// Total processing time in milliseconds
    #[schema(example = 5230)]
    pub total_time_ms: u64,
}

impl From<reasondb_ingest::IngestStats> for IngestStats {
    fn from(s: reasondb_ingest::IngestStats) -> Self {
        Self {
            chars_extracted: s.chars_extracted,
            chunks_created: s.chunks_created,
            nodes_created: s.nodes_created,
            summaries_generated: s.summaries_generated,
            total_time_ms: s.total_time_ms,
        }
    }
}

/// Internal job-queue payload for text ingestion.
///
/// Not exposed as an API request body — use `IngestTextBody` instead.
/// The `table_id` field holds the resolved UUID written by the handler before enqueue.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngestTextRequest {
    pub title: String,
    pub content: String,
    pub table_id: String,
    #[serde(default)]
    pub generate_summaries: Option<bool>,
    #[serde(default)]
    pub tags: Option<Vec<String>>,
    #[serde(default)]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Chunking strategy override: "agentic" or "markdown_aware"
    #[serde(default)]
    pub chunk_strategy: Option<String>,
}

/// Body for table-scoped text ingestion (table name comes from the URL path)
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct IngestTextBody {
    /// Document title
    #[schema(example = "My Research Notes")]
    pub title: String,
    /// Document content (plain text or Markdown)
    #[schema(example = "# Introduction\n\nThis document covers...")]
    pub content: String,
    /// Whether to generate LLM summaries (default: true)
    #[serde(default)]
    pub generate_summaries: Option<bool>,
    /// Document tags for filtering
    #[serde(default)]
    #[schema(example = json!(["nda", "confidential"]))]
    pub tags: Option<Vec<String>>,
    /// Custom metadata (key-value pairs)
    #[serde(default)]
    #[schema(example = json!({"contract_type": "nda", "value_usd": 50000}))]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Chunking strategy: "agentic" (default) or "markdown_aware"
    #[serde(default)]
    #[schema(example = "agentic")]
    pub chunk_strategy: Option<String>,
}

/// Internal job-queue payload for URL ingestion.
///
/// Not exposed as an API request body — use `IngestUrlBody` instead.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngestUrlRequest {
    pub url: String,
    pub table_id: String,
    #[serde(default)]
    pub generate_summaries: Option<bool>,
    /// Chunking strategy override: "agentic" or "markdown_aware"
    #[serde(default)]
    pub chunk_strategy: Option<String>,
}

/// Body for table-scoped URL ingestion (table name comes from the URL path)
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct IngestUrlBody {
    /// URL to ingest (web page, YouTube video, etc.)
    #[schema(example = "https://en.wikipedia.org/wiki/Machine_learning")]
    pub url: String,
    /// Whether to generate LLM summaries (default: true)
    #[serde(default)]
    pub generate_summaries: Option<bool>,
    /// Chunking strategy: "agentic" (default) or "markdown_aware"
    #[serde(default)]
    #[schema(example = "agentic")]
    pub chunk_strategy: Option<String>,
}

/// Core file ingestion logic — saves the upload to a persistent temp path, enqueues an
/// async job, and returns immediately with a job ID for polling.
async fn ingest_file_inner<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    state: Arc<AppState<R>>,
    filename: String,
    data: Vec<u8>,
    raw_table_id: String,
) -> ApiResult<Json<JobStatusResponse>> {
    if !state.reasoner.is_ingestion_healthy() {
        return Err(ApiError::ServiceUnavailable(
            "LLM ingestion provider is currently unhealthy. \
             Verify your LLM configuration with POST /v1/config/llm/test. \
             The provider will auto-recover in up to 60 seconds after the issue is resolved."
                .to_string(),
        ));
    }

    let table_id = state
        .store
        .resolve_table_id(&raw_table_id)
        .map_err(ApiError::from)?;
    state
        .store
        .get_table(&table_id)
        .map_err(ApiError::from)?
        .ok_or_else(|| ApiError::NotFound(format!("Table '{}' not found", raw_table_id)))?;

    info!(
        "Queuing file ingestion: {} ({} bytes) into table: {}",
        filename,
        data.len(),
        table_id
    );

    // Write the upload to a persistent temp path. A unique prefix ensures no
    // collisions between concurrent uploads. The worker deletes the file after
    // processing (success or failure).
    let upload_id = uuid::Uuid::new_v4().simple().to_string();
    let temp_path = std::env::temp_dir().join(format!("reasondb_{}_{}", upload_id, filename));
    std::fs::write(&temp_path, &data)
        .map_err(|e| ApiError::Internal(format!("Failed to write temp file: {}", e)))?;

    let file_req = IngestFileRequest {
        filename,
        temp_path: temp_path
            .to_str()
            .ok_or_else(|| ApiError::Internal("Non-UTF8 temp path".to_string()))?
            .to_string(),
        table_id,
        generate_summaries: Some(state.config.generate_summaries),
        tags: None,
        metadata: None,
        chunk_strategy: None,
    };

    let enqueued_id = state
        .job_queue
        .enqueue(JobRequest::File(file_req))
        .map_err(ApiError::Internal)?;

    let status = state
        .job_queue
        .get_status(&enqueued_id)
        .ok_or_else(|| ApiError::Internal("Job not found after enqueue".to_string()))?;

    info!("File ingestion queued as job {}", enqueued_id);

    Ok(Json(status))
}

/// Extract file bytes from a multipart request, enforcing the max upload size.
async fn extract_file_from_multipart<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    state: &AppState<R>,
    mut multipart: Multipart,
) -> ApiResult<(String, Vec<u8>)> {
    let mut file_data: Option<(String, Vec<u8>)> = None;

    while let Some(field) = multipart
        .next_field()
        .await
        .map_err(|e| ApiError::BadRequest(format!("Failed to read multipart: {}", e)))?
    {
        if field.name().unwrap_or("") == "file" {
            let filename = field
                .file_name()
                .map(|s| s.to_string())
                .unwrap_or_else(|| "unknown".to_string());

            let data = field
                .bytes()
                .await
                .map_err(|e| ApiError::BadRequest(format!("Failed to read file: {}", e)))?;

            if data.len() > state.config.max_upload_size {
                return Err(ApiError::BadRequest(format!(
                    "File too large. Max size: {} bytes",
                    state.config.max_upload_size
                )));
            }

            file_data = Some((filename, data.to_vec()));
        }
    }

    file_data.ok_or_else(|| ApiError::BadRequest("No file provided".to_string()))
}

/// Ingest a file into a specific table (multipart upload — async)
///
/// Upload a document file for background ingestion. The file is saved and
/// a job is enqueued immediately. Poll `GET /v1/jobs/{job_id}` for progress
/// and the resulting document ID.
///
/// Supported formats depend on the registered extractor plugins (e.g. the
/// built-in `markitdown` plugin covers PDF, Word, Excel, PowerPoint,
/// images, audio, HTML, and more). The multipart body only needs the `file`
/// field.
#[utoipa::path(
    post,
    path = "/v1/tables/{table_name}/ingest/file",
    tag = "ingestion",
    params(("table_name" = String, Path, description = "Table name or slug")),
    request_body(content_type = "multipart/form-data", description = "File to ingest"),
    responses(
        (status = 202, description = "File ingestion job queued", body = JobStatusResponse),
        (status = 400, description = "Invalid request", body = ErrorResponse),
        (status = 404, description = "Table not found", body = ErrorResponse),
        (status = 500, description = "Failed to queue ingestion", body = ErrorResponse),
    )
)]
pub async fn ingest_file_for_table<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    State(state): State<Arc<AppState<R>>>,
    Path(table_name): Path<String>,
    multipart: Multipart,
) -> ApiResult<Json<JobStatusResponse>> {
    let (filename, data) = extract_file_from_multipart(&state, multipart).await?;
    ingest_file_inner(state, filename, data, table_name).await
}

/// Core text ingestion logic — resolves the table and enqueues a job.
async fn ingest_text_inner<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    state: Arc<AppState<R>>,
    mut request: IngestTextRequest,
) -> ApiResult<Json<JobStatusResponse>> {
    if !state.reasoner.is_ingestion_healthy() {
        return Err(ApiError::ServiceUnavailable(
            "LLM ingestion provider is currently unhealthy. \
             Verify your LLM configuration with POST /v1/config/llm/test. \
             The provider will auto-recover in up to 60 seconds after the issue is resolved."
                .to_string(),
        ));
    }

    if request.title.is_empty() {
        return Err(ApiError::ValidationError("Title is required".to_string()));
    }
    if request.content.is_empty() {
        return Err(ApiError::ValidationError("Content is required".to_string()));
    }
    if request.table_id.is_empty() {
        return Err(ApiError::ValidationError(
            "Table ID is required".to_string(),
        ));
    }

    let raw_table_id = request.table_id.clone();
    request.table_id = state
        .store
        .resolve_table_id(&raw_table_id)
        .map_err(ApiError::from)?;
    state
        .store
        .get_table(&request.table_id)
        .map_err(ApiError::from)?
        .ok_or_else(|| ApiError::NotFound(format!("Table '{}' not found", raw_table_id)))?;

    info!(
        "Queuing text ingestion: {} ({} chars) into table: {}",
        request.title,
        request.content.len(),
        request.table_id
    );

    let job_id = state
        .job_queue
        .enqueue(JobRequest::Text(request))
        .map_err(ApiError::Internal)?;
    let status = state
        .job_queue
        .get_status(&job_id)
        .ok_or_else(|| ApiError::Internal("Job not found after enqueue".to_string()))?;

    Ok(Json(status))
}

/// Ingest raw text or Markdown into a specific table (async — returns a job ID)
///
/// Enqueues text for background ingestion. The content will be chunked,
/// organized into a tree structure, and optionally summarized by the LLM.
/// Poll `GET /v1/jobs/{job_id}` for progress and the resulting document ID.
#[utoipa::path(
    post,
    path = "/v1/tables/{table_name}/ingest/text",
    tag = "ingestion",
    params(("table_name" = String, Path, description = "Table name or slug")),
    request_body = IngestTextBody,
    responses(
        (status = 202, description = "Ingestion job queued", body = JobStatusResponse),
        (status = 404, description = "Table not found", body = ErrorResponse),
        (status = 422, description = "Validation failed", body = ErrorResponse),
    )
)]
pub async fn ingest_text_for_table<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    State(state): State<Arc<AppState<R>>>,
    Path(table_name): Path<String>,
    Json(body): Json<IngestTextBody>,
) -> ApiResult<Json<JobStatusResponse>> {
    ingest_text_inner(
        state,
        IngestTextRequest {
            title: body.title,
            content: body.content,
            table_id: table_name,
            generate_summaries: body.generate_summaries,
            tags: body.tags,
            metadata: body.metadata,
            chunk_strategy: body.chunk_strategy,
        },
    )
    .await
}

/// A single item in a batch ingestion request
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct BatchIngestItem {
    /// Document title
    #[schema(example = "My Research Notes")]
    pub title: String,
    /// Document content (plain text or Markdown)
    #[schema(example = "# Introduction\n\nThis document covers...")]
    pub content: String,
    /// Whether to generate LLM summaries (default: true)
    #[serde(default)]
    pub generate_summaries: Option<bool>,
    /// Document tags for filtering
    #[serde(default)]
    #[schema(example = json!(["nda", "confidential"]))]
    pub tags: Option<Vec<String>>,
    /// Custom metadata (key-value pairs)
    #[serde(default)]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Chunking strategy: "agentic" (default) or "markdown_aware"
    #[serde(default)]
    #[schema(example = "agentic")]
    pub chunk_strategy: Option<String>,
}

/// Body for table-scoped batch ingestion (table name comes from the URL path)
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct BatchIngestBody {
    /// Array of documents to ingest
    pub documents: Vec<BatchIngestItem>,
}

/// Response for batch ingestion
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct BatchIngestResponse {
    /// Number of jobs created
    pub jobs_created: usize,
    /// Job IDs for polling
    pub job_ids: Vec<String>,
}

/// Core batch ingestion logic — resolves the table and enqueues one job per document.
async fn ingest_batch_inner<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    state: Arc<AppState<R>>,
    raw_table_id: String,
    documents: Vec<BatchIngestItem>,
) -> ApiResult<Json<BatchIngestResponse>> {
    if !state.reasoner.is_ingestion_healthy() {
        return Err(ApiError::ServiceUnavailable(
            "LLM ingestion provider is currently unhealthy. \
             Verify your LLM configuration with POST /v1/config/llm/test. \
             The provider will auto-recover in up to 60 seconds after the issue is resolved."
                .to_string(),
        ));
    }

    if raw_table_id.is_empty() {
        return Err(ApiError::ValidationError(
            "Table ID is required".to_string(),
        ));
    }
    if documents.is_empty() {
        return Err(ApiError::ValidationError(
            "At least one document is required".to_string(),
        ));
    }

    let resolved_table_id = state
        .store
        .resolve_table_id(&raw_table_id)
        .map_err(ApiError::from)?;
    state
        .store
        .get_table(&resolved_table_id)
        .map_err(ApiError::from)?
        .ok_or_else(|| ApiError::NotFound(format!("Table '{}' not found", raw_table_id)))?;

    info!(
        "Queuing batch ingestion: {} documents into table: {}",
        documents.len(),
        resolved_table_id
    );

    let mut job_ids = Vec::with_capacity(documents.len());

    for item in documents {
        if item.title.is_empty() || item.content.is_empty() {
            continue;
        }

        let text_req = IngestTextRequest {
            title: item.title,
            content: item.content,
            table_id: resolved_table_id.clone(),
            generate_summaries: item.generate_summaries,
            tags: item.tags,
            metadata: item.metadata,
            chunk_strategy: item.chunk_strategy,
        };

        let job_id = state
            .job_queue
            .enqueue(JobRequest::Text(text_req))
            .map_err(ApiError::Internal)?;

        job_ids.push(job_id);
    }

    info!("Batch enqueued {} jobs", job_ids.len());

    Ok(Json(BatchIngestResponse {
        jobs_created: job_ids.len(),
        job_ids,
    }))
}

/// Ingest multiple documents into a specific table (async — returns job IDs)
///
/// Enqueues multiple documents for background ingestion into the same table.
/// Each document becomes a separate job that can be polled individually via
/// `GET /v1/jobs/{job_id}`.
#[utoipa::path(
    post,
    path = "/v1/tables/{table_name}/ingest/batch",
    tag = "ingestion",
    params(("table_name" = String, Path, description = "Table name or slug")),
    request_body = BatchIngestBody,
    responses(
        (status = 202, description = "Batch ingestion jobs queued", body = BatchIngestResponse),
        (status = 404, description = "Table not found", body = ErrorResponse),
        (status = 422, description = "Validation failed", body = ErrorResponse),
    )
)]
pub async fn ingest_batch_for_table<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    State(state): State<Arc<AppState<R>>>,
    Path(table_name): Path<String>,
    Json(body): Json<BatchIngestBody>,
) -> ApiResult<Json<BatchIngestResponse>> {
    ingest_batch_inner(state, table_name, body.documents).await
}

/// Core URL ingestion logic — resolves the table and enqueues a job.
async fn ingest_url_inner<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    state: Arc<AppState<R>>,
    mut request: IngestUrlRequest,
) -> ApiResult<Json<JobStatusResponse>> {
    if !state.reasoner.is_ingestion_healthy() {
        return Err(ApiError::ServiceUnavailable(
            "LLM ingestion provider is currently unhealthy. \
             Verify your LLM configuration with POST /v1/config/llm/test. \
             The provider will auto-recover in up to 60 seconds after the issue is resolved."
                .to_string(),
        ));
    }

    if request.url.is_empty() {
        return Err(ApiError::ValidationError("URL is required".to_string()));
    }
    if request.table_id.is_empty() {
        return Err(ApiError::ValidationError(
            "Table ID is required".to_string(),
        ));
    }

    url::Url::parse(&request.url)
        .map_err(|e| ApiError::ValidationError(format!("Invalid URL: {}", e)))?;

    let raw_table_id = request.table_id.clone();
    request.table_id = state
        .store
        .resolve_table_id(&raw_table_id)
        .map_err(ApiError::from)?;
    state
        .store
        .get_table(&request.table_id)
        .map_err(ApiError::from)?
        .ok_or_else(|| ApiError::NotFound(format!("Table '{}' not found", raw_table_id)))?;

    info!(
        "Queuing URL ingestion: {} into table: {}",
        request.url, request.table_id
    );

    let job_id = state
        .job_queue
        .enqueue(JobRequest::Url(request))
        .map_err(ApiError::Internal)?;
    let status = state
        .job_queue
        .get_status(&job_id)
        .ok_or_else(|| ApiError::Internal("Job not found after enqueue".to_string()))?;

    Ok(Json(status))
}

/// Ingest from a URL into a specific table (async — returns a job ID)
///
/// Enqueues a URL for background ingestion. Supports web pages, YouTube
/// videos (with transcription), and other online resources. Poll
/// `GET /v1/jobs/{job_id}` for progress and the resulting document ID.
#[utoipa::path(
    post,
    path = "/v1/tables/{table_name}/ingest/url",
    tag = "ingestion",
    params(("table_name" = String, Path, description = "Table name or slug")),
    request_body = IngestUrlBody,
    responses(
        (status = 202, description = "Ingestion job queued", body = JobStatusResponse),
        (status = 404, description = "Table not found", body = ErrorResponse),
        (status = 422, description = "Validation failed (invalid URL)", body = ErrorResponse),
    )
)]
pub async fn ingest_url_for_table<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    State(state): State<Arc<AppState<R>>>,
    Path(table_name): Path<String>,
    Json(body): Json<IngestUrlBody>,
) -> ApiResult<Json<JobStatusResponse>> {
    ingest_url_inner(
        state,
        IngestUrlRequest {
            url: body.url,
            table_id: table_name,
            generate_summaries: body.generate_summaries,
            chunk_strategy: body.chunk_strategy,
        },
    )
    .await
}

// ==================== Chunks ingestion ====================

/// A single pre-split chunk with free-form metadata.
///
/// Well-known metadata keys: `page_number`, `start_line`, `end_line`, `section_type`.
/// Any other keys are stored in `NodeMetadata.attributes`.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct ChunkBodyItem {
    /// The text content of this chunk
    #[schema(example = "This section covers the introduction to the topic...")]
    pub text: String,
    /// Optional heading / title for this chunk. Used as the node title.
    #[serde(default)]
    #[schema(example = "Introduction")]
    pub heading: Option<String>,
    /// Optional pre-computed summary. If provided, the LLM summarization step
    /// is skipped for this node. If absent, a summary is auto-generated.
    #[serde(default)]
    #[schema(example = "Introduces the core concepts of the topic.")]
    pub summary: Option<String>,
    /// Free-form metadata — pass any key-value pairs.
    /// Well-known keys: page_number (u32), start_line (u32), end_line (u32), section_type (string).
    /// All other keys are stored in NodeMetadata.attributes.
    #[serde(default)]
    #[schema(example = json!({"page_number": 1, "start_line": 10, "end_line": 25, "source": "pdfplumber"}))]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
}

/// Body for pre-chunked ingestion (table name comes from the URL path)
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct IngestChunksBody {
    /// Document title
    #[schema(example = "My Research Paper")]
    pub title: String,
    /// Optional document description (stored in document metadata)
    #[serde(default)]
    #[schema(example = "A paper about machine learning techniques")]
    pub description: Option<String>,
    /// Pre-split text chunks with their metadata
    pub chunks: Vec<ChunkBodyItem>,
    /// Document tags for filtering
    #[serde(default)]
    #[schema(example = json!(["research", "ml"]))]
    pub tags: Option<Vec<String>>,
    /// Document-level metadata (key-value pairs)
    #[serde(default)]
    #[schema(example = json!({"author": "Alice", "year": 2026}))]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
}

/// Internal job-queue payload for pre-chunked ingestion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IngestChunksRequest {
    pub title: String,
    pub table_id: String,
    pub chunks: Vec<ChunkBodyItem>,
    #[serde(default)]
    pub tags: Option<Vec<String>>,
    #[serde(default)]
    pub metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
}

/// Ingest pre-chunked content into a specific table (async — returns a job ID)
///
/// Accepts an array of text chunks with optional per-chunk metadata.
/// Bypasses the extraction and chunking stages — content is fed directly
/// into the tree builder and summarizer. Per-chunk metadata (e.g.
/// `start_line`, `end_line`, `page_number`) is preserved on each node.
#[utoipa::path(
    post,
    path = "/v1/tables/{table_name}/ingest/chunks",
    tag = "ingestion",
    params(("table_name" = String, Path, description = "Table name or slug")),
    request_body = IngestChunksBody,
    responses(
        (status = 202, description = "Ingestion job queued", body = JobStatusResponse),
        (status = 404, description = "Table not found", body = ErrorResponse),
        (status = 422, description = "Validation failed", body = ErrorResponse),
    )
)]
pub async fn ingest_chunks_for_table<R: ReasoningEngine + Clone + Send + Sync + 'static>(
    State(state): State<Arc<AppState<R>>>,
    Path(table_name): Path<String>,
    Json(body): Json<IngestChunksBody>,
) -> ApiResult<Json<JobStatusResponse>> {
    let table_id = state
        .store
        .resolve_table_id(&table_name)
        .map_err(ApiError::from)?;

    state
        .store
        .get_table(&table_id)
        .map_err(ApiError::from)?
        .ok_or_else(|| ApiError::NotFound(format!("Table '{}' not found", table_name)))?;

    info!(
        "Queuing chunks ingestion: '{}' ({} chunks) into table: {}",
        body.title,
        body.chunks.len(),
        table_id
    );

    let request = IngestChunksRequest {
        title: body.title,
        table_id,
        chunks: body.chunks,
        tags: body.tags,
        metadata: body.metadata,
    };

    let job_id = state
        .job_queue
        .enqueue(JobRequest::Chunks(request))
        .map_err(ApiError::Internal)?;

    let status = state
        .job_queue
        .get_status(&job_id)
        .ok_or_else(|| ApiError::Internal("Job not found after enqueue".to_string()))?;

    Ok(Json(status))
}
